# Generated by Django 4.0.1 on 2022-01-14 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exchange_app', '0005_alter_userapi_email'),
    ]

    operations = [
        migrations.RenameField(
            model_name='userapi',
            old_name='uniswapApi',
            new_name='uniswapPrivate',
        ),
        migrations.RenameField(
            model_name='userapi',
            old_name='uniswapSecret',
            new_name='uniswapPublic',
        ),
    ]
